# Generated by Django 3.2.2 on 2021-05-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authore',
            new_name='author',
        ),
    ]
